ALTER TABLE identity_schema.users
ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN DEFAULT FALSE;

ALTER TABLE identity_schema.users
ADD COLUMN IF NOT EXISTS mfa_type VARCHAR(30) DEFAULT 'NONE';

ALTER TABLE identity_schema.users
ADD COLUMN IF NOT EXISTS mfa_secret VARCHAR(255);